name: Build Documentation

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Download Doxygen Awesome Theme
        run: wget https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css

      - name: Configure Doxygen
        run: |
          doxygen -g
          sed -i 's/PROJECT_NAME           = "My Project"/PROJECT_NAME           = "HoloLib"/g' Doxyfile
          sed -i 's/INPUT                  =/INPUT                  = include/g' Doxyfile
          sed -i 's/RECURSIVE              = NO/RECURSIVE              = YES/g' Doxyfile
          # EXCLUDE THIRD-PARTY DEPENDENCIES
          sed -i 's|EXCLUDE_PATTERNS      =|EXCLUDE_PATTERNS      = */Eigen/* */pros/* */okapi/*|g' Doxyfile
          sed -i 's/GENERATE_HTML          = NO/GENERATE_HTML          = YES/g' Doxyfile
          sed -i 's/GENERATE_LATEX         = YES/GENERATE_LATEX         = NO/g' Doxyfile
          sed -i 's/GENERATE_TREEVIEW      = NO/GENERATE_TREEVIEW      = YES/g' Doxyfile
          sed -i 's/HTML_EXTRA_STYLESHEET  =/HTML_EXTRA_STYLESHEET  = doxygen-awesome.css/g' Doxyfile

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
